# Generated by Django 4.0.3 on 2022-03-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='day_of_week',
            field=models.CharField(max_length=20),
        ),
    ]
